repos:
  - repo: https://github.com/pre-commit/mirrors-yapf/
    rev: v0.30.0
    hooks:
      - id: yapf
        files: ^(core|handlers|libs|tests)/.*\.py$
        args:
          - --diff
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        files: ^(core|handlers|libs|tests)/.*\.py$
  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        files: ^(core|handlers|libs|tests)/.*\.py$
        args:
          - --errors-only
          - --disable=import-error
