repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        files: ^(core|handlers|libs|tests)/.*\.py$
        args:
          - --diff
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        files: ^(core|handlers|libs|tests)/.*\.py$
        args:
          - --max-line-length=88
          - --ignore=E203,E501,W504,E126,E24,E704,E121,E226,E123,W503
  - repo: git://github.com/pre-commit/mirrors-pylint
    rev: v2.5.3
    hooks:
      - id: pylint
        files: ^(core|handlers|libs|tests)/.*\.py$
        args:
          - --errors-only
          - --disable=import-error
