"""Remove JSONType

Revision ID: accf99394c8c
Revises: 8df0a9a19a5e
Create Date: 2021-10-19 11:35:52.737686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'accf99394c8c'
down_revision = '8df0a9a19a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
