"""Added user.data

Revision ID: 22be7ca598f1
Revises: 8df0a9a19a5e
Create Date: 2021-10-19 22:51:14.400991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22be7ca598f1'
down_revision = '8df0a9a19a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
